yaml
name: Save Bot History

on:
  schedule:
    # Запускать каждые 30 минут
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Разрешить ручной запуск

jobs:
  save-history:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Download current stats
      run: |
        # Скачиваем текущий JSON
        curl -s -o current.json https://raw.githubusercontent.com/dimb9ih/dimb9ih.github.io/master/ifbot_stats.json
        
        # Проверяем, что файл не пустой
        if [ -s current.json ]; then
          echo "✅ JSON downloaded successfully"
          cat current.json | jq '.timestamp_human' || echo "Could not parse JSON"
        else
          echo "❌ Failed to download JSON"
          exit 1
        fi
        
    - name: Create history directory
      run: |
        # Создаем папки для истории
        mkdir -p history
        mkdir -p history/daily
        
        echo "Created history directories"
        
    - name: Save history file
      run: |
        # Создаем уникальное имя файла
        TIMESTAMP=$(date -u +"%Y%m%d_%H%M%S")
        FILENAME="ifbot_${TIMESTAMP}.json"
        
        # Также создаем папку для дня
        DATE_FOLDER=$(date -u +"%Y/%m/%d")
        DAILY_PATH="history/daily/${DATE_FOLDER}"
        mkdir -p "${DAILY_PATH}"
        
        # Копируем файл в обе папки
        cp current.json "history/${FILENAME}"
        cp current.json "${DAILY_PATH}/${FILENAME}"
        
        echo "📁 Saved to: history/${FILENAME}"
        echo "📁 Daily copy: ${DAILY_PATH}/${FILENAME}"
        
        # Создаем index файл со списком всех файлов
        ls -1 history/ifbot_*.json | sort -r > history/index.txt
        wc -l history/index.txt
        
    - name: Clean old files (keep last 1000)
      run: |
        # Сохраняем только последние 1000 файлов
        cd history
        FILES_COUNT=$(ls ifbot_*.json | wc -l)
        
        if [ $FILES_COUNT -gt 1000 ]; then
          echo "Cleaning old files... ($FILES_COUNT > 1000)"
          # Удаляем самые старые файлы
          ls -1 ifbot_*.json | sort | head -n $(($FILES_COUNT - 1000)) | xargs rm -f
          echo "Removed $(($FILES_COUNT - 1000)) old files"
        else
          echo "No cleaning needed ($FILES_COUNT files)"
        fi
        
    - name: Create summary JSON
      run: |
        # Создаем сводный файл для быстрой загрузки
        python3 -c "
import json
import os
from datetime import datetime, timedelta

# Получаем файлы за последние 24 часа
files = []
for f in os.listdir('history'):
    if f.startswith('ifbot_') and f.endswith('.json'):
        try:
            # Извлекаем время из имени файла
            ts_str = f[6:21]  # ifbot_YYYYMMDD_HHMMSS.json
            dt = datetime.strptime(ts_str, '%Y%m%d_%H%M%S')
            if datetime.now() - dt < timedelta(days=1):
                files.append(f)
        except:
            pass

# Читаем каждый файл и извлекаем ключевые данные
data_points = []
for f in sorted(files)[-96:]:  # Последние 96 точек (24 часа * 4 в час)
    try:
        with open(f'history/{f}', 'r') as file:
            data = json.load(file)
            
            point = {
                't': data.get('timestamp', 0),
                'cpu': data.get('system_stats', {}).get('cpu', {}).get('utilization_percent', 0),
                'ram': data.get('system_stats', {}).get('memory', {}).get('utilization_percent', 0),
                'errors': data.get('error_stats', {}).get('errors', 0),
                'warnings': data.get('error_stats', {}).get('warnings', 0),
                'cycle': data.get('cycle_count', 0),
                'battery': int(data.get('battery_info', {}).get('battery_level', 0))
            }
            
            if point['t'] > 0:
                data_points.append(point)
    except:
        pass

# Сохраняем сводный файл
summary = {
    'last_update': datetime.now().isoformat(),
    'data_points': data_points,
    'total_points': len(data_points)
}

with open('history/summary_24h.json', 'w') as f:
    json.dump(summary, f, indent=2)

print(f'Created summary with {len(data_points)} data points')
"
        
    - name: Commit and push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add history/
        git commit -m "🤖 Auto-save bot history - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push origin HEAD:master
